name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'packages/frontend/mobile/package-lock.json'

    - name: Install dependencies
      run: |
        cd packages/frontend/mobile
        npm ci

    - name: Run linting
      run: |
        cd packages/frontend/mobile
        npm run lint

    - name: Run tests
      run: |
        cd packages/frontend/mobile
        npm test

    - name: Build
      run: |
        cd packages/frontend/mobile
        npm run build